---
- name: Install httpd
  hosts: all
  become: yes

  tasks:
    - name: Install httpd
      yum:
        name:
        - httpd
        state: present

    - name: Install homepage
      copy:
        content: "<h1>Foo bar</h1>"
        dest: /var/www/html/index.html
        backup: yes

    - name: Start service and enabled
      service:
        name: httpd
        enabled: yes
        state: started

    - name: permit traffic in default zone for https service
      firewalld:
        service: http
        permanent: yes
        state: enabled
